# Generated by Django 4.2.7 on 2023-11-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update',
            new_name='updated',
        ),
    ]
